version: "3.9"

services:

  iplay4:
    image: iplay4:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iplay4
    restart: always
    volumes:
      - "${IPLAY4_PLAYLISTS}:/opt/iplay4/web/playlists"
      - "${IPLAY4_ARCHIVE}:/media/arch"
    ports:
      - "8999:8000"
